services:
  postgis:
    image: postgis/postgis
    ports:
      - 15432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - type: bind
        source: ./demo.sql
        target: /docker-entrypoint-initdb.d/demo.sql
  geoserver:
    image: docker.osgeo.org/geoserver:2.28.x
    ports:
      - 18080:8080
    volumes:
      - geoserver_data:/opt/geoserver_data
  arcsde-proxy:
    build: ./plugins/catalog-backend-module-arcgis-sde-data/src/sde-python-proxy/
    ports:
      - 8045:8045
    volumes:
      - ./plugins/catalog-backend-module-arcgis-sde-data/src/sde-python-proxy/:/app
volumes:
  geoserver_data: