site_name: GeoPortia
site_url: https://eskilstuna-kommun.github.io/geoportia
copyright: "&copy; Eskilstuna municipality and other contributors"
site_description: Metadata & service administration for geodata
repo_url: https://github.com/Eskilstuna-kommun/geoportia
theme:
  name: material
  language: en
  features:
    - content.action.edit
    - navigation.footer
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
  icon:
    repo: fontawesome/brands/github
plugins:
  - privacy
  - search
  - include-markdown
#  - social
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.keys
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 4
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
nav:
  - Home:
    - index.md
    - licens.md
  - Use:
    - use/index.md
    - Get Started:
      - Automatic Schema Updates: use/get-started/postgresql/automatic-schema-updates.md