apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: my-pg-database
  title: Local PostgreSQL (development)
  description: Local PostgreSQL database used in development.
  tags:
    - postgresql
    - database
  links:
    - title: Connection host
      url: postgres://localhost:15432/postgres
spec:
  type: database
  owner: group:default/geoportia-team
  system: geoportia
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: my-arcgis-sde-database
  title: Local ArcGIS SDE (development)
  description: Local ArcGIS SDE database used in development.
  tags:
    - arcgis
    - sde
    - database
spec:
  type: database
  owner: group:default/geoportia-team
  system: geoportia
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ag-analys
  title: AG_Analys
  description: "Arbetsmarknads- och vuxenutbildningsförvaltningen, Arbete och försörjning"
  tags:
    - database
  annotations:
    geoportia.se/host-name: AG_Analys
    geoportia.se/status: Godkänd
spec:
  type: database
  owner: "group:default/geoportia-team"
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: test
  title: test
  description: "STASH (Sweco TEM Application Subscription Handling) är att
    underlätta för produktägaren vid hanteringen av återkommande abonnemang och
    göra en direktkoppling till TEM för att slippa återkommande manuell
    hantering. "
  tags:
    - database
  annotations:
    geoportia.se/host-name: AG_Analys
    geoportia.se/status: Godkänd
spec:
  type: database
  owner: group:default/geoportia-team
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: test1
  title: test1
  description: "STASH (Sweco TEM Application Subscription Handling) är att
    underlätta för produktägaren vid hanteringen av återkommande abonnemang och
    göra en direktkoppling till TEM för att slippa återkommande manuell
    hantering. "
  tags:
    - database
  annotations:
    geoportia.se/host-name: AG_Analys
    geoportia.se/status: Godkänd
spec:
  type: database
  owner: group:default/geoportia-team
