---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-user
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: sweco-sedalh
spec:
  memberOf: [users]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: sweco-seohfr
spec:
  memberOf: [users]
---
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: sweco-seyemi
spec:
  memberOf: [users]
---
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: sweco-se1g7y
spec:
  memberOf: [users, GG-U-Roll-GeoPortia-Admin]
---
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: JohnKohlin
spec:
  memberOf: [users]
---
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: Dalneberg
spec:
  memberOf: [users]
---
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: Grammostola
spec:
  memberOf: [users]
---
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: sweco-se1c8x
spec:
  memberOf: [users, GG-U-Roll-GeoPortia-SuperAdmin]
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: users
spec:
  type: team
  children: []
---
# GeoPortia Role Groups
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: GG-U-Roll-GeoPortia-SuperAdmin
  description: Full access including sensitive data
spec:
  type: role
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: GG-U-Roll-GeoPortia-Admin
  description: Full access except sensitive data
spec:
  type: role
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: GG-U-Roll-GeoPortia-Moderator
  description: Read all, edit main geodata only (no delete)
spec:
  type: role
  children: []
